services:
  server:
    build:
      context: ..
      dockerfile: apps/server/Dockerfile

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
      args:
        BUILD_REVISION: ${IMAGE_TAG:-local}
